import HomePage from '@/components/HomePage';
import Head from 'next/head';
// import { useAuthContext } from 'context/AuthContext';
// import useProfileStore from 'store/profile';

export default function Home() {
  // HOW TO: use app context
  // const {auth} = useAuthContext();

  // HOW TO: use zustand
  // const { user } = useProfileStore();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  );
}
